#!/usr/bin/env bash

set -euo pipefail

react-native bundle --reset-cache --dev false --entry-file index.husk.js --bundle-output release2.jsbundle.tmp

cat release2.jsbundle.tmp | \
    perl -pe 's|RE_NATAL_PLACEHOLDER|"(function(require){\n\n".`cat index.ios.js`."\n\n})"|ge' > release2.jsbundle
